module.exports = {
    articlesWidget:    require('./articles_widget'),
    accountMenu:       require('./account_menu'),
    betslipWidget:     require('./betslip'),
    cashoutWidget:    require('./cashout_widget'),
    comingEventsWidget:require('./coming_events_widget'), 
    footer:            require('./footer'),
    highlightsWidget:  require('./highlights_widget'),
    i18nWidget:        require('./i18n_widget'),
    leftMenu:   	   require('./left_menu'),
    liveMenu:          require('./live_menu'),
    liveChatWidget:    require('./live_chat_widget'),
    nextGamesWidget:   require('./next_games_widget'),
    newsWidget:        require('./news_widget'),
    mainMenu:          require('./main_menu'),
    rightMenu:   	   require('./right_menu'),
    slideChatWidget:   require('./slide_chat'),
    sportsMenu:  	   require('./sports_menu'),
    socialWidget:      require('./social_widget'),
    upcomingGames:     require('./upcoming_games_widget'),
    userMenu:          require('./user_menu'),
    virtualBetslipWdiget: require('./virtuals_betslip'),
    liveMatchesWidget: require('./live_matches_widget'),
    favoriteEventsWidget: require('./favorite_events_widget'),
    popularEventsWidget: require('./popular_events_widget'),
    loyalty: require('./loyalty_widget'),
    popularCombineWidget: require('./popular_combine_widget')  
}
